import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import {
  type PostCandidate,
  fetchClient,
  fetchPendingCandidates,
  approveCandidate,
  rejectCandidate,
  type ClientSummary,
} from "../services/api";

export const ClientApprovalsPage = () => {
  const { clientId } = useParams<{ clientId: string }>();
  const [client, setClient] = useState<ClientSummary | null>(null);
  const [candidates, setCandidates] = useState<PostCandidate[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [submittingId, setSubmittingId] = useState<number | null>(null);

  useEffect(() => {
    if (!clientId) return;
    let cancelled = false;

    const load = async () => {
      try {
        const [clientData, candidateData] = await Promise.all([
          fetchClient(clientId),
          fetchPendingCandidates(clientId),
        ]);
        if (!cancelled) {
          setClient(clientData);
          setCandidates(candidateData);
        }
      } catch (err: any) {
        if (!cancelled) {
          setError(err?.message || "Failed to load approvals");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    load();
    return () => {
      cancelled = true;
    };
  }, [clientId]);

  const handleApprove = async (id: number) => {
    setSubmittingId(id);
    try {
      await approveCandidate(id);
      setCandidates((prev) => prev.filter((c) => c.id !== id));
    } catch (err: any) {
      alert(err?.message || "Failed to approve post");
    } finally {
      setSubmittingId(null);
    }
  };

  const handleReject = async (id: number) => {
    const reason = window.prompt("Reason for rejection? (optional)") || undefined;
    setSubmittingId(id);
    try {
      await rejectCandidate(id, reason);
      setCandidates((prev) => prev.filter((c) => c.id !== id));
    } catch (err: any) {
      alert(err?.message || "Failed to reject post");
    } finally {
      setSubmittingId(null);
    }
  };

  if (loading) return <p>Loading approvals…</p>;
  if (error) return <p className="error-text">{error}</p>;
  if (!client) return <p>Client not found.</p>;

  return (
    <div>
      <div className="page-header">
        <div>
          <h1>Approvals · {client.name}</h1>
          <p className="muted">
            Review and approve upcoming posts generated by Postify.
          </p>
        </div>
        <div className="page-header-actions">
          <Link to={`/clients/${client.id}`} className="btn">
            Back to overview
          </Link>
        </div>
      </div>

      {candidates.length === 0 ? (
        <p>No pending posts right now 🎉</p>
      ) : (
        <div className="card-column">
          {candidates.map((cand) => (
            <article key={cand.id} className="card">
              <p className="muted">
                Template: <strong>{cand.template_key}</strong> · Slot:{" "}
                {new Date(cand.slot_time).toLocaleString()}
              </p>
              <p className="post-body">{cand.text_body}</p>

              <div className="card-actions">
                <button
                  className="btn"
                  disabled={submittingId === cand.id}
                  onClick={() => handleReject(cand.id)}
                >
                  ❌ Reject
                </button>
                <button
                  className="btn primary"
                  disabled={submittingId === cand.id}
                  onClick={() => handleApprove(cand.id)}
                >
                  ✅ Approve
                </button>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  );
};
